name: "Run TODO to Issue"
on: ["push"]
jobs:
  scan-todos:
    runs-on: "ubuntu-latest"
    permissions:
      issues: write
    steps:
      - uses: "actions/checkout@v4"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v5"
        with:
          IDENTIFIERS: '[{"name": "TODO", "labels": ["todo"], "filter": "^TODO: .{150,}"}]'
